### PR TITLE
Wrote a simple HBR note parser and quiz generator

### PR DESCRIPTION
**Pull request by kuc2477**
This PR mainly consists of 2 parts:
1. `parser.py` and `generator.py` for parsing your HBR notes and generating quiz out of them.
2. `__init__.py` which runs a simple HTTP server to serve quiz page in your browser.

Simply running `pip install -r requirements.txt && python takequiz.py` should work both on Windows and *NIX-like systems (I've only tested on Windows though).

Although the `Parser` class in `parser.py` is designed with any possible structures (단어, 문장, etc.) in mind, currently it's working poorly on 문장 target especially.

 I'm looking forward to improve the parsing logic and add extra quiz related features (collecting and visualizing quiz results etc.). 

Would be really happy to see this little PR being merged into your master branch.

 Thanks.

image

image

image

### CODE REVIEW

**Comment by kuc2477** [comment]
fixing parser logic for 문장 target. closing the PR for a moment.

**Comment by kuc2477** [comment]
Fixed parsing logic for 문장 target. Note that this PR works only on Python 3+ because of the unicode support issue on Python2.

**Comment by theverytak** [comment]
Thank you!

**Comment by theverytak** [comment]
There's some words on pending, which I couldn't get. I will find the adequate Korean meaning soon.

**Pull request merged**
